### ISSUE TITLE
FreeBSD 11.1: bad check for presence of sudo

### ISSUE THREAD

**Issue by adriaandegroot** [RainbowHackerHorse/vzvol#19]
Using `pkg -N info | grep sudo` to check for the presence of sudo is likely to hit false positives, e.g. with various sudoku programs installed. `pkg -N info -e sudo` is probably a better bet.

**Comment by adriaandegroot** [comment]
Similar checks are in *freebsd/vzvol_pkgcheck.sh*, although i expect fewer false positives with those, see e.g. https://www.freshports.org/search.php?query=e2fsprogs

**Comment by RainbowHackerHorse** [comment]
Good point. I'll be moving to check binary location directly on disk. This is already planned for the next patch.
