### ISSUE TITLE
FreeBSD 11.1: tries to su when it doesn't need to

### ISSUE THREAD

**Issue by adriaandegroot** [RainbowHackerHorse/vzvol#20]
When running vzvol as root, the su command should probably be left blank / do nothing, since there's no need to su. Something like this, perhaps:

```
if [ 0 = $( id -u ) ] ; then
    VZVOL_SU_CMD=sudo_do_nothing
    # Execute the command passed in, with no wrapping
    sudo_do_nothing() {
        "$@"
    }
fi
```

**Comment by adriaandegroot** [comment]
.. one (only?) case where this happens is in `shared/vzvol_permissions.sh` where there's a *zfs set custom:fs=none* .. command not guarded by a check for ZROOT != root. That's why using a shell-function for su might be better, you can lose the guards elsewhere in the scripts and systematically use $VZVOL_SU_CMD everywhere.

**Comment by RainbowHackerHorse** [comment]
CLosing as this functionality will be removed shortly to rely only on sudo, and will check if already running as root
