### ISSUE TITLE
FreeBSD 11.1: inconsistent use of $HOME (for root)

### ISSUE THREAD

**Issue by adriaandegroot** [RainbowHackerHorse/vzvol#22]
I can create a volume with a virtualbox shin:

```
root@beastie:/home/user # vzvol -s 1G -t virtualbox -p zarray -v whatevs
Testing to ensure zvol was created
Creating /home/root/VBoxdisks/whatevs.vmdk
RAW host disk access VMDK file /home/root/VBoxdisks/whatevs.vmdk created successfully.
Please use /home/root/VBoxdisks/whatevs.vmdk as your VM Disk
```

Root's home directory is */root*, though. Running `vzvol --list` doesn't show me the associated VMDK, because that code is looking in the actual home-dir, so it's looking for `/root/VBoxdisks/` which doesn't exist.

**Comment by RainbowHackerHorse** [comment]
Fixed.
