### ISSUE TITLE
FreeBSD 11.1: incorrect use of su -c

### ISSUE THREAD

**Issue by adriaandegroot** [RainbowHackerHorse/vzvol#23]
When run as a user, without sudo, VZVOL_SU_CMD is set to "su - root -c"; there's another issue filed about how this expands badly. But su is different from sudo in that it expects **one** parameter as the command, so a command like this one:

```
$ su - root -c zfs set custom:fs=none zbigone/whatevs3
```

goes on to fail. Using a shell function does the trick:

```
VZVOL_SU_CMD=sudo_do_su
sudo_do_su() {
su - root -c "$*"
}
```

Using vzvol in combination with su is a pain in the butt, though, since it'll run su four times during creation, so I get asked for my root password four times (ugh, but not your problem -- this is one reason why sudo was invented).

Anyway, this is my last GH issue: knowing that `-t` is mandatory, knowing to run it from somewhere where there isn't a `../lib` in the way, with this shell function for su purposes, vzvol ticks an awful lot of boxes for me. Thanks. (I feel bad for dogpiling on you like this, please take this as an overenthusiastic "oh boy, cool tool that I really want to use" combined with me being a numbskull when using the tool.)

**Comment by RainbowHackerHorse** [comment]
Hey, no worries, these are issues I didn't catch, and I knew some stuff would crop up once others were using vzvol in a real world scenario!
I appreciate you taking the time to open these!
Oddly enough, not using -t should indeed cause the command to fail. I may have accidentally deleted the check at one point....

Anyway!
the su issue.
Yeah, I really don't like the way it works right now. I wanted this to be as no-dependency as possible, but being that some major functionality depends on other programs anyway, I think it's time to give up that fight, switch to depend on sudo, and remove the "use su to fake sudo" code.
